version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5100:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - JWT_SECRET=SuperSecretSimonMovilidadKey2026SecureStringWithMoreBytes
      - SIGNALR_URL=http://localhost:5100/telemetryHub
      - DB_PATH=/app/data/fleet.db
    volumes:
      - db-data:/app/data

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "4220:80"
    depends_on:
      - backend

volumes:
  db-data:
